### ISSUE TITLE
two presentations in one project?

### ISSUE THREAD

**Issue by guaka** [markdalgleish/generator-bespoke#21]
It would be nice to have two (or more) presentations in one project. Is this possible?

E.g. `index.jade` is the main presentation, but `another-one.jade` could be accessible through `/another-one.html`.

**Comment by markdalgleish** [comment]
I'm sure it's possible, but beyond the scope of what this project is aiming to achieve. I'm closing this issue, but please add a comment with a link to your repo if you manage to achieve this.
